from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

SKIDL_lib_version = '0.0.1'

test_design_lib = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'keywords':'cap capacitor', 'F0':'C', 'datasheet':'~', 'description':'Unpolarized capacitor', 'F1':'C', 'ref_prefix':'C', 'num_units':1, 'fplist':['C_*'], 'do_erc':True, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'input', 'dest':TEMPLATE, 'tool':SKIDL, 'keywords':'connector', 'F0':'J', 'datasheet':'~', 'description':'Generic shielded connector, single row, 01x06, script generated (kicad-library-utils/schlib/autogen/connector/)', 'F1':'Conn_01x06_Shielded', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??-1SH*'], 'do_erc':True, 'footprint':'gkl_conn:5034800600', 'pins':[
            Pin(num='1',name='Pin_1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='Pin_2',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='Pin_3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='Pin_4',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='Pin_5',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='Pin_6',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='SH',name='Shield',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'output', 'dest':TEMPLATE, 'tool':SKIDL, 'keywords':'connector', 'F0':'J', 'datasheet':'~', 'description':'Generic shielded connector, single row, 01x06, script generated (kicad-library-utils/schlib/autogen/connector/)', 'F1':'Conn_01x06_Shielded', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??-1SH*'], 'do_erc':True, 'footprint':'gkl_conn:5034800600', 'pins':[
            Pin(num='1',name='Pin_1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='Pin_2',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='Pin_3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='Pin_4',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='Pin_5',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='Pin_6',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='SH',name='Shield',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'LED_ARGB', 'dest':TEMPLATE, 'tool':SKIDL, 'keywords':'LED RGB diode', 'F0':'D', 'datasheet':'~', 'description':'RGB LED, anode/red/green/blue', 'F1':'LED_ARGB', 'ref_prefix':'D', 'num_units':1, 'fplist':['LED*', 'LED_SMD:*', 'LED_THT:*'], 'do_erc':True, 'footprint':'gkl_led:led_rbag_1515_dense', 'pins':[
            Pin(num='1',name='A',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='RK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='GK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='BK',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'TLC59025', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'TLC59025', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'gkl_misc:SSOP-24_slim', 'pins':[
            Pin(num='1',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='10',name='OUT5',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='11',name='OUT6',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='12',name='OUT7',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='13',name='OUT8',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='14',name='OUT9',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='15',name='OUT10',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='16',name='OUT11',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='17',name='OUT12',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='18',name='OUT13',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='19',name='OUT14',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='2',name='SDI',func=Pin.types.INPUT,do_erc=True),
            Pin(num='20',name='OUT15',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='21',name='~OE',func=Pin.types.INPUT,do_erc=True),
            Pin(num='22',name='SDO',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='23',name='R-EXT',func=Pin.types.INPUT,do_erc=True),
            Pin(num='24',name='VDD',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='3',name='CLK',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='LE',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='OUT0',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='6',name='OUT1',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='7',name='OUT2',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='8',name='OUT3',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='9',name='OUT4',func=Pin.types.OUTPUT,do_erc=True)] }),
        Part(**{ 'name':'74HC595', 'dest':TEMPLATE, 'tool':SKIDL, 'keywords':'TTL SR 3State', 'F0':'U', 'datasheet':'http://www.ti.com/lit/gpn/sn74ls595', 'description':'8-bit serial in/out Shift Register 3-State Outputs', 'F1':'74HC595', '_aliases':Alias({'74HCT595', '74LS595'}), 'ref_prefix':'U', 'num_units':1, 'fplist':['DIP*W7.62mm*', 'SOIC*3.9x9.9mm*P1.27mm*', 'TSSOP*4.4x5mm*P0.65mm*', 'SOIC*5.3x10.2mm*P1.27mm*', 'SOIC*7.5x10.3mm*P1.27mm*'], 'do_erc':True, 'aliases':Alias({'74HCT595', '74LS595'}), 'footprint':'gkl_misc:TSSOP-16_slim', 'pins':[
            Pin(num='1',name='QB',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='10',name='~SRCLR',func=Pin.types.INPUT,do_erc=True),
            Pin(num='11',name='SRCLK',func=Pin.types.INPUT,do_erc=True),
            Pin(num='12',name='RCLK',func=Pin.types.INPUT,do_erc=True),
            Pin(num='13',name='~OE',func=Pin.types.INPUT,do_erc=True),
            Pin(num='14',name='SER',func=Pin.types.INPUT,do_erc=True),
            Pin(num='15',name='QA',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='16',name='VCC',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='2',name='QC',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='3',name='QD',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='4',name='QE',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='5',name='QF',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='6',name='QG',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='7',name='QH',func=Pin.types.TRISTATE,do_erc=True),
            Pin(num='8',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='9',name="QH'",func=Pin.types.OUTPUT,do_erc=True)] }),
        Part(**{ 'name':'Q_PMOS_GSD', 'dest':TEMPLATE, 'tool':SKIDL, 'keywords':'transistor PMOS P-MOS P-MOSFET', 'F0':'Q', 'datasheet':'~', 'description':'P-MOSFET transistor, gate/source/drain', 'F1':'Q_PMOS_GSD', 'ref_prefix':'Q', 'num_units':1, 'do_erc':True, 'footprint':'Package_TO_SOT_SMD:SOT-883', 'pins':[
            Pin(num='1',name='G',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='S',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='D',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'keywords':'R res resistor', 'F0':'R', 'datasheet':'~', 'description':'Resistor', 'F1':'R', 'ref_prefix':'R', 'num_units':1, 'fplist':['R_*'], 'do_erc':True, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'pins':[
            Pin(num='1',name='~',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='~',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'NC7WZ17', 'dest':TEMPLATE, 'tool':SKIDL, 'F0':'U', 'F1':'NC7WZ17', 'ref_prefix':'U', 'num_units':1, 'do_erc':True, 'footprint':'gkl_misc:UDFN-6_1x1mm_P0.35mm', 'pins':[
            Pin(num='1',name='A1',func=Pin.types.INPUT,do_erc=True),
            Pin(num='2',name='GND',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='A2',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='Y2',func=Pin.types.OUTPUT,do_erc=True),
            Pin(num='5',name='VCC',func=Pin.types.INPUT,do_erc=True),
            Pin(num='6',name='Y1',func=Pin.types.OUTPUT,do_erc=True)] })])